// src/components/profile/EditProfileForm.tsx
export const DEFAULT_MOTTOS = [
  "✨ Radiating positivity",
  "🌱 Growing daily",
  "🔮 Listening to my inner voice",
  "🔥 Fueled by purpose",
  "🌟 Shining from within",
  "💖 Guided by love",
  "🧘‍♀️ Embracing balance",
  "🌊 Flowing with ease",
  "🌿 Rooted in gratitude",
  "🌈 Attracting abundance",
  "💡 Illuminating my path",
  "🌸 Blossoming in authenticity",
  "🌞 Embracing each sunrise",
  "🌙 Dreaming in technicolor",
  "⚡ Charging forward fearlessly",
  "🤝 Thriving in community",
  "🌀 Trusting my intuition",
  "🌻 Growing toward the light",
];
